### PR TITLE
Update Quanta T41 and D51 skupacks

### PR DESCRIPTION
**Pull request by zyoung51**
@RackHD/corecommitters @uppalk1 @keedya @tannoa2

### CODE REVIEW

**Comment by heckj** [comment]
not sure about how this gets packaged - should there be duplicates of the quanta-t41 workflows in the quanta-d51 as well?

**Comment by zyoung51** [comment]
The current product mapper reference implementation has only the T41 populated.  The actual work of ensuring these flows function is another task: https://www.pivotaltracker.com/projects/1492890/stories/115968947

**Comment by heckj** [comment]
cool

**Comment by yyscamper** [comment]
:+1:

**Comment by tannoa2** [comment]
+1

**Pull request merged**
