### PR TITLE
Addd enable/disable BIOS VTx attribute workflows

### PR DESCRIPTION
**Pull request by pengz1**
Addd enable/disable BIOS VTx attribute workflows for dell servers.
dell-c6320, dell-r630, dell-r730 skupacks are updated.

### CODE REVIEW

**Comment by pengz1** [comment]
@RackHD/corecommitters @cgx027

**Comment by cgx027** [comment]
Looks good :+1:

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
@pengz1 if move from on-taskgraph to on-skupack, suggest to remove contents in on-taskgraph to avoid duplication

**Comment by pengz1** [comment]
@anhou . I am OK to remove those tasks/graphs. However it will be more convenient to keep them before we move to 2.0 API. Otherwise we need to inject SKU PACK each time we want to use those graphs. After all there are many other sku-specified workflows, we can clean them up after 2.0 API is ready.

**Comment by anhou** [comment]
@pengz1 it doesn't have relationship with 2.0 API. we'll have a functionality that SKU pack loading at build time. it will be discussed in next CC meeting. you can refer to https://github.com/RackHD/RackHD/wiki/Core-Committer-Meeting  If you could make sure that don't forget to update/remove this duplicate workflow when this functionality is brought in. it's also fine. if not , it may have a process fo issue-> fix -> verified until that time.  Just keep in mind that no one knows/remember this duplication except you.

**Comment by pengz1** [comment]
@anhou . My point is keeping them will make it more convenient before we can loading SKU pack during build. And if loading SKU pack at build is ready, we need not just move dell graphs to SKU pack, but all the other SKU related( like Quanta, Cisco, Intel and other ) out of on-taskgraph repo.
And you are right no one can identify all SKU-specified graphs without digging some details, so it is worthy a dedicated and thoroughly cleanup for all SKU specified workflows. No graphs should be left at that time.

**Comment by anhou** [comment]
@pengz1 so SKU related( Quanta, Cisco,  Intel ) you said is duplicated for on-skupack and on-taskgraph at present?

**Comment by pengz1** [comment]
@anhou If you notice, there are still lots of SKU-Specified workflows in on-taskgraph repo, they are in the same position with all dell graphs.

**Comment by anhou** [comment]
@pengz1 my point is not about cleanup, is about no duplication (codes maintained by two places), if you think it's convenient that graphs located in on-taskgraph. why need this PR, just submit it that time(cleanup?). so either on-taskgraph or on-skupack, choose one.

**Pull request closed without merging**
