### PR TITLE
Fix to Arista config.json file

### PR DESCRIPTION
**Pull request by pscharla**
Fix bug in the Arista 7124S config.json file.

@benbp @heckj @gpaulos

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by benbp** [comment]
👍

**Comment by pscharla** [comment]
fixes https://github.com/RackHD/RackHD/issues/264

**Comment by pscharla** [comment]
closes https://github.com/RackHD/RackHD/issues/264

**Pull request merged**
