### PR TITLE
Fix some sel alerts in the skupacks

### PR DESCRIPTION
**Pull request by tannoa2**
Fixing https://hwjiraprd01.corp.emc.com/browse/ODR-909

### CODE REVIEW

**Comment by tannoa2** [comment]
@jlongever @RackHD/corecommitters @uppalk1 @amymullins @keedya @hohene @larry-dean @zyoung51

**Review by brianparry — APPROVED** [review]
:+1:

**Comment by srinia6** [comment]
+1

**Comment by larry-dean** [comment]
-1
What about the dell-r730xd?

**Comment by tannoa2** [comment]
@deanl1 added the dell one

**Comment by larry-dean** [comment]
+1 with the addition of the dell

**Pull request merged**
