### PR TITLE
Remove Platform-R

### PR DESCRIPTION
**Pull request by zyoung51**

### CODE REVIEW

**Comment by yyscamper** [comment]
@zyoung51 : the intention of this PR is to move platform-x skupack to internal?

**Comment by zyoung51** [comment]
@yyscamper Yes

**Comment by yyscamper** [comment]
@zyoung51 : how about to remove platform-r-tp and platform-H as well? So we can avoid open additional PRs.

**Comment by zyoung51** [comment]
@yyscamper This already does remove platform-r-tp.  Platform-H is not part of this task.

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
