### PR TITLE
modify flash update feature for quanta

### PR DESCRIPTION
**Pull request by iceiilin**
Change the keyword "file" to "imageFile" to avoid confilict with RackHD build-in keyword imported for static file server.
Modify the format of md5 from api/2.0/files api to remove quotes from the result , otherwise the md5 result would be '"xxx"', which could not be tested equal with the calculated value.
Remove flash bmc task which is unused in the current workflow.

### CODE REVIEW

**Review by nortonluo — APPROVED** [review]
Leave a comment

**Review by stuart-stanley — COMMENTED** [review]
Um, doesn't this break all existing users of this skupack?

**Comment by iceiilin** [comment]
@stuart-stanley actually if not adding this change, the FW update feature with user specified external FW file is broken and won't work since late 2016.

**Comment by stuart-stanley** [comment]
I'm still nervous about changing the API signature rather than fixing the rackhd code. I'll approve the request and let you decide if this is our only choice for this.

**Review by stuart-stanley — APPROVED** [review]

**Comment by iceiilin** [comment]
@stuart-stanley it doesn't actually change its md5 value, but to remove its quotes. The schema for api/2.0/files/<name>/md5 was implemented in https://github.com/RackHD/on-http/blob/master/data/views/files.md5.2.0.json in the late 2016, and I think it is reasonable to keep it as it is and consistent with other api response.

**Pull request merged**
