### PR TITLE
Quanta d51 skupack story

### PR DESCRIPTION
**Pull request by uppalk1**
Firmware update feature add for BIOS, BMC.

### CODE REVIEW

**Comment by yyscamper** [comment]
Just want to confirm a question: Are we sure want to put the raw FW image into the on-skupack repository? @zyoung51 @jlongever

**Comment by uppalk1** [comment]
no, I will remove it. That wasn't intentional.

**Comment by yyscamper** [comment]
@uppalk1 , OK, :+1: after remove the binary files.

**Comment by jlongever** [comment]
+1

**Pull request merged**
